# Generated by Django 3.0.2 on 2020-02-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runexp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
