# Generated by Django 3.0.2 on 2020-03-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runexp', '0004_auto_20200229_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='filename',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
